Add Bazelisk tests runs as a pre-condition to pushing to the remote repo.

diff --git a/dev/hooks/pre-push b/dev/hooks/pre-push
--- a/dev/hooks/pre-push
+++ b/dev/hooks/pre-push
@@ -1,3 +1,8 @@
-echo "lol"
+#!/bin/bash
+# An exit status of 1 means that tests failed to run.
 
-exit 1
+$(git rev-parse --show-toplevel)/dev/run_all_tests.sh || {
+  echo "-------------------------------------------------------------------------------"
+  echo "Push halted due to test failures."
+  exit 1
+}
